{
"integrations": {
  
  },
  "update_behavior": {
    "auto_start_updates": "no",
    "skip_manual_testing": "no",
    "source_branch": "dev",
    "destination_branch": "updates0123/[task:id]"
  },
  "events": {
    "new_updates_available": [
      {
        "sendmail": {
          "emails": "alexey.beloglazov@app-guard.io",
          "subject": "New updates available for \"[project:name]\"",
          "message": "We've found the new updates for your project.<br><br>The packages:<br>[task:packages|,][package:name]: [package:current-version] â†’ [package:new-version][/task:packages]<br><br>[task:url]",
          "cc": "",
          "bcc": ""
        }
      }
    ],
    "ready_to_test": [

    ],
    "test_passed": [
      {
        "merge_branch": {
          "source": "updates/[task:id]",
          "delete_after_merge": "yes",
          "target": ["dev"]
        }
      }
    ],
    "failed": [
      {
        "sendmail": {
          "emails": "alexey.beloglazov@app-guard.io",
          "subject": "The problems have been detected in \"[project:name]\" project",
          "message": "Unfortunately, during processing the task something went wrong.<br><br>[task:url]",
          "cc": "",
          "bcc": ""
        }
      }
    ],
    "patch_cant_be_applied": [
      {
        "sendmail": {
          "emails": "alexey.beloglazov@app-guard.io",
          "subject": "The updates couldn't be applied in \"[project:name]\" project",
          "message": "Unfortunately, something we couldn't apply the update for your task.<br><br>[task:url]",
          "cc": "",
          "bcc": ""
        }
      }
    ]
  }
}